<div class="wrap">
    <img src='<?php echo $this->getViewFileUrl('images/004-delivery-truck-silhouette.svg'); ?>' height="30"
         width="30"
         alt=""/>
    <div class="adds">
        <strong><a href="#">Free Delivery!</a></strong>
        <p>On orders over $100</p>
    </div>
</div>

<div class="wrap">
    <img src='<?php echo $this->getViewFileUrl('images/003-gift.svg'); ?>' height="30" width="30"
         alt="">
    <div class="adds">
        <strong><a href="#">Choose a free gifts!</a></strong>
        <p>With every purchase</p>
    </div>
</div>

<div class="wrap">
    <img src='<?php echo $this->getViewFileUrl('images/006-padlock.svg'); ?>' height="30" width="30"
         alt="">
    <div class="adds">
        <strong><a href="#">100% secure shopping!</a></strong>
        <p>Top security</p>
    </div>
</div>



