<div class="wrap">
    <img src='<?php echo $this->getViewFileUrl('images/004-delivery-truck-silhouette.svg'); ?>' height="30"
         width="30"
         alt=""/>
    <div class="adds">
        <strong><a href="#"><?= __('Free Delivery!') ?>
            </a></strong>
        <p><?= __('On orders over $100') ?></p>
    </div>
</div>

<div class="wrap">
    <img src='<?php echo $this->getViewFileUrl('images/003-gift.svg'); ?>' height="30" width="30"
         alt="">
    <div class="adds">
        <strong><a href="#"><?= __('Choose a free gifts!') ?></a></strong>
        <p><?= __('With every purchase') ?></p>
    </div>
</div>

<div class="wrap">
    <img src='<?php echo $this->getViewFileUrl('images/006-padlock.svg'); ?>' height="30" width="30"
         alt="">
    <div class="adds">
        <strong><a href="#"><?= __('100% secure shopping!') ?></a></strong>
        <p><?= __('Top security') ?></p>
    </div>
</div>



