<div class="cards">
    <img src='<?php echo $this->getViewFileUrl('images/cc-mastercard-brands.svg'); ?>' height="40"
         width="60"
         alt=""/>
    <img src='<?php echo $this->getViewFileUrl('images/cc-paypal-brands.svg'); ?>' height="40"
         width="60"
         alt=""/>
    <img src='<?php echo $this->getViewFileUrl('images/cc-visa-brands.svg'); ?>' height="40"
         width="60"
         alt=""/>
</div>